steps:
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: [ 'pull', 'gcr.io/$PROJECT_ID/builder-collection-server' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'gcr.io/$PROJECT_ID/collection-server' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--cache-from', 'gcr.io/$PROJECT_ID/builder-collection-server',
            '-t', 'gcr.io/$PROJECT_ID/builder-collection-server',
            '--target', 'builder',
            '-f', 'Dockerfile', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build'
            '--cache-from', 'gcr.io/$PROJECT_ID/builder-collection-server',
            '--cache-from', 'gcr.io/$PROJECT_ID/collection-server',
            '-t', 'gcr.io/$PROJECT_ID/collection-server',
            '-t', 'gcr.io/$PROJECT_ID/collection-server:$BRANCH_NAME',
            '-t', 'gcr.io/$PROJECT_ID/collection-server:$COMMIT_SHA',
            '-f', 'Dockerfile', '.' ]

images:
  - 'gcr.io/$PROJECT_ID/builder-collection-server'
  - 'gcr.io/$PROJECT_ID/collection-server'
  - 'gcr.io/$PROJECT_ID/collection-server:$BRANCH_NAME'
  - 'gcr.io/$PROJECT_ID/collection-server:$COMMIT_SHA'

timeout: 30m
